### ISSUE TITLE
hostoutput stdout is incomplete for centos/redhat

### ISSUE THREAD

**Issue by fliepeltje** [CentreForDigitalHumanities/humitifier#46]
Known facts:

- The task runs are successful - so not an issue with rocketry
- The output for the debian hosts is always working
- The output for centos/redhat is never correct
  - It either cuts off just before or `hostnamectl` or just after (not including the `hostnamectl` output)
  - It doesn't get output at all
  - The `HostOutput` yields no exception, so the command executes fine but reading stdout is somehow limited

**Comment by bartbouter** [comment]
Added the client.join() function to wait and collect the output of all the cmds run by pssh

https://github.com/ParallelSSH/parallel-ssh#waiting-for-completion-and-exit-codes
https://parallel-ssh.readthedocs.io/en/latest/advanced.html?highlight=client.join#join-and-output-timeouts
