### ISSUE TITLE
doubled entries

### ISSUE THREAD

**Issue by falconburrow** [CentreForDigitalHumanities/humitifier#52]
I noticed some machines which are doubled in reports; example:

https://humitifier.hum.uu.nl/?fqdn=gw-d-rsl-parseport-acc&os=&alert=&package=containerd.io&department=&contact=

**Comment by fliepeltje** [comment]
This is due to these machines being duplicated in the config

![image](https://github.com/CentreForDigitalHumanities/humitifier/assets/49225672/6add0f73-6593-4d33-8ad1-4cd1f1533509)
