### ISSUE TITLE
Non-functioning filters

### ISSUE THREAD

**Issue by 73616e646572** [CentreForDigitalHumanities/humitifier#57]
Filters `Select departement` and `Select contact` do not present any options and can't be typed in.

![image](https://github.com/CentreForDigitalHumanities/humitifier/assets/6605233/9cd16737-feaf-4cef-aca6-2e0b37fb2bf6)

**Comment by fliepeltje** [comment]
![image](https://github.com/CentreForDigitalHumanities/humitifier/assets/49225672/8b967f2a-139a-407b-a7fa-4bd1920cde6e)

Works on my machine :+1: (fixed with recent update)
