### ISSUE TITLE
Check puppet agent status

### ISSUE THREAD

**Issue by bartbouter** [CentreForDigitalHumanities/humitifier#59]
1. Add the ability to check on the puppet agent status. enabled or disabled

When te agent is disabled ( and no puppet runs are done ) a file is created in /opt/puppetlabs/puppet/cache/state/agent_disabled.lock
A check if this file exists should do the magic.

2. Add an critical alert if the puppet agent is disabled

**Comment by fliepeltje** [comment]
Implemented in f89d2ca67485331c81d4ef59aa9e8703988110b4
